######################################################################
# This is auto-generated by wio
######################################################################

set(CMAKE_VER 3.0.0)
set(PROJECT_NAME {{PROJECT_NAME}})
set(PROJECT_PATH "{{PROJECT_PATH}}")
set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR})
set(DEPENDENCY_FILE dependencies)
set(CMAKE_CXX_STANDARD 11)

# Properties
set(TARGET_NAME {{TARGET_NAME}})
set(ENTRY {{ENTRY}})

# CMAKE
cmake_minimum_required(VERSION ${CMAKE_VERSION})
project(${PROJECT_NAME} C CXX ASM)

file(GLOB_RECURSE ${TARGET_NAME}_files
    ${PROJECT_PATH}/${ENTRY}/*.cpp
    ${PROJECT_PATH}/${ENTRY}/*.cc
    ${PROJECT_PATH}/${ENTRY}/*.c)

add_executable(${TARGET_NAME} ${${TARGET_NAME}_files})

target_compile_definitions(
    ${TARGET_NAME}
    PRIVATE
    WIO_PLATFORM_${PLATFORM}
    WIO_FRAMEWORK_${FRAMEWORK}
    WIO_BOARD_${BOARD}
    {{TARGET_COMPILE_DEFINITIONS}})

target_compile_options(
    ${TARGET_NAME}
    PRIVATE
    {{TARGET_COMPILE_FLAGS}})

include(${DEPENDENCY_FILE})
