#!/bin/bash
#!/usr/bin/env bash

export COSA_DIR=$(cd -P -- "$(dirname -- "$0")" && pwd -P)/platform/cosa
export GCC_AVR_VER=gcc-avr-4.2
export PATH=$PATH:$COSA_DIR/build/cosa

set -o nounset
set -o errexit

trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR

set -o errtrace
set -o pipefail

DEFAULT_IFS="${IFS}"
SAFER_IFS=$'\n\t'
IFS="${SAFER_IFS}"

_ME=$(basename "${0}")

_print_help() {
  cat <<HEREDOC
                 __               .__
__  _  _______ _/  |_  ___________|  |   ____   ____ ______
\ \/ \/ /\__  \\   __\/ __ \_  __ \  |  /  _ \ /  _ \ \____ \
 \     /  / __ \|  | \  ___/|  | \/  |_(  <_> |  <_> )  |_> >
  \/\_/  (____  /__|  \___  >__|  |____/\____/ \____/|   __/
              \/          \/                         |__|
The Embedded C++ code base builder
Usage:
  ${_ME} [help] [boards]
Options:
  help               Show this screen.
  boards             Show available boards.
HEREDOC
}

_simple() {
    root_dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
    root_dir_name=$(basename "$root_dir")
    cd "$root_dir"

    if [ "$1" == 'boards' ] ; then
        $COSA_DIR/build/cosa boards

    else
        _print_help
    fi
}

_main() {
    if [[ "${1:-}" =~ ^h|help$  ]] || [ $# -lt "1" ] ; then
        _print_help
    else
        _simple "$@"
    fi
}

_main "$@"
