#!/bin/bash
#!/usr/bin/env bash

set -o errexit
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR
set -o errtrace
set -o pipefail
DEFAULT_IFS="${IFS}"
SAFER_IFS=$'\n\t'
IFS="${SAFER_IFS}"
_ME=$(basename "${0}")

_print_help() {
  cat <<HEREDOC
                 __               .__
__  _  _______ _/  |_  ___________|  |   ____   ____ ______
\\ \\/ \\/ /\\__  \\\\   __\\/ __ \\_  __ \\  |  /  _ \\ /  _ \\\\____ \\
 \\     /  / __ \\|  | \\  ___/|  | \\/  |_(  <_> |  <_> )  |_> >
  \\/\\_/  (____  /__|  \\___  >__|  |____/\\____/ \\____/|   __/
              \\/          \\/                         |__|
Waterloop code base builder
HEREDOC
}

#### Variables ####
GO_VERSION=1.1[1-9]
TRAVIS=false

_build() {
    make build
}

_clean() {
    make clean
}

_get() {
    make get
}

_linux_setup() {
    # Check go version
    command -v go > /dev/null 2>&1 || {
        echo 'go is not installed';
        exit 1;
    }
    go version | grep ${GO_VERSION} &> /dev/null
    if [ $? != 0 ] ; then
        echo 'go version 1.1x is required where x is >= 1';
        exit 1;
    fi

    printf "Initiating submodules...\n"
    git submodule update --init --recursive

    printf "Retrieving dependencies...\n"
    make get

    printf "Installing system library... "
    go get -u golang.org/x/sys/unix
    printf "Done!\n"

    printf "Getting dep dependencies... "
    dep ensure
    printf "Done!\n"

    printf "Linking test vendor packages... "
    cd test
    ./symlinks.sh
    cd ..
    printf "Done!\n"

    printf "Installing gotools..."
    if [ "$TRAVIS" = false ] ; then
        go get -u golang.org/x/tools/...
    fi

    printf "Done!\n"
}

_avr_setup() {
    apt-get update
    apt-get install gcc-avr avr-libc avrdude
}

_format() {
    command -v goimports > /dev/null 2>&1 || {
        echo 'goimports is not installed';
        exit 1;
    }
    command -v vim > /dev/null 2>&1 || {
        echo 'vim is not installed';
        exit 1;
    }

    printf "Running gofmt... "
    find cmd pkg internal -type f -name "*.go" -exec \
        goimports -w {} \;
    printf "Done!\nRunning retab... "
    find cmd pkg internal -type f -name "*.go" -exec \
        vim -e -s +"set tabstop=4 shiftwidth=4 expandtab | retab | %s/\s\+$//e | wq" {} \;
    printf "Done!\n"
}

_test() {
    cd test
    ./runtests.sh
}

_release() {
    # create build files
    cd ./deploy/gen
    go run cross-build.go

    # create a tag
    printf "Creating release tag $1...\n"
    git tag -a "$1" -m "$2"
    git push "$3" "$1"

    # download relaser library and create release tag
    printf "Creating Github Release...\n" 
    go get -u github.com/aktau/github-release
    github-release release \
        --user wio \
        --repo wio \
        --tag "$1" \
        --name "$1" \
        --description "$2"
    
    # upload files
    printf "Pushing binaries to the Release...\n"
    cd ./bin
    for file in *; do
        printf "  Uploading $file...\n"
        github-release upload \
            --user wio \
            --repo wio \
            --tag "$1" \
            --name "$file" \
            --file "$file"
    done

    printf "Project $1 Successfully Released!\n"
}

_simple() {
    root_dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
    root_dir_name=$(basename "$root_dir")
    cd "$root_dir"

    if [ "$1" == 'build' ] ; then
        echo "Building project"
        _build
    elif [ "$1" == 'clean' ] ; then
        echo "Cleaning project"
        _clean
    elif [ "$1" == 'get' ] ; then
        echo "Getting packages"
        _get
    elif [ "$1" == 'linux-setup' ] ; then
        echo "Setting up environment for Linux"
        _linux_setup
    elif [ "$1" == 'mac-setup' ]; then
        echo "Setting up environment for Mac OS"
        _linux_setup
    elif [ "$1" == 'travis-setup' ] ; then
        echo "Setting up environment for Travis CI"
        TRAVIS=true
        _linux_setup
    elif [ "$1" == 'avr-setup' ] ; then
        echo "Installing AVR development dependencies"
        _avr_setup
    elif [ "$1" == 'format' ] ; then
        echo "Formatting wio codebase"
        _format
    elif [ "$1" == 'test' ] ; then
        _test
    elif [ "$1" == 'release' ] ; then
         if [ $# -le 3 ] ; then
            echo "Provide tag name, tag description and git remote"
            exit 3
         fi
        printf "Releasing wio\n"
        _release $2 $3 $4
    else
        _print_help
    fi
}

_main() {
  # Avoid complex option parsing when only one program option is expected.
  if [[ "${1:-}" =~ ^-h|--help$  ]] || [ $# -lt "1" ]
  then
    _print_help
  else
    _simple "$@"
  fi
}

_main "$@"
